saltyfacu/ape-tax

src/config.js
Kevin's keeperDAO, sell ROOK for DAI strategy.
=> feat: add old grandmaster's dai

src/App.vue, src/Home.vue, src/NotFound.vue, src/Vault.vue
=> feat: add network switcher

README.md, package-lock.json, package.json, scripts/newVault.js
Add a script to be able to safely add a vault to the json file.
This script works with a default interactive way and support multiple option (to be easy to integrate with another script).
It will prompt for the needed elements and edit the `vaults.json` file to append the new vault.
Some elements will be fetched from the desired desired blockchain and from coingecko (`WANT_SYMBOL`, `COINGECKO_SYMBOL`, `WANT_ADDR`) and a `--fast` option is available to set  `VAULT_ABI`, `VAULT_TYPE` and `VAULT_STATUS` to their default value.
To add a new vault to the list, you need to run the following command : `node scripts/newVault.js --fast`.  
This will prompt you with several information:  
- What's the name of your vault ? (*ex: Hardrock Farmer*)
- What's the logo for your vault ? (*ex: 🎸👨‍🌾*)
- …
=> Feature/addVault Script

src/vaults.json
set old, deprecated vaults to `withdraw` and prod vaults to `endorsed`
=> feat: Clean up vaults

utils/vaults.json
Update TUSD, COMP, SUSHI, and AAVE prod vaults
=> feat: move vaults to prod

pages/[slug]/index.js
Fixing the depositAll option to trigger MM
If you balance of want token > 0, then the deposit button should not be disabled, and onClick, the transaction should be triggered
=> BugFix/Allow depositAll

contexts/useWeb3.js, next.config.js, pages/[slug]/index.js, utils/API.js
Replace the user's RPC by our RPC for request on FMT network to be sure to get the APY (if available).  
We are now always using `https://rpc.ftm.tools` to get vaults data on FMT
The vault's APY on fantom should always be displayed
=> Feature/Fantom RPC use

utils/vaults.json
Set Fantom Bitcoin and Tied Tyler as withdraw vaults
=> Vaults/Withdraw Fantom Bitcoin & Tied Tyler

utils/vaults.json
Just changed the emoji wand to a magic ball  for windows users.
=> Windows_is_Lesser

utils/vaults.json
* New yvLUSD vault
* Strategy that deposits LUSD to Liquity's Stability Pool
* Auto-compound LQTY and ETH gains fore more LUSD
* Has a cool name
=> feat: yvLUSD vault on ethereum mainnet

utils/vaults.json
- new yvWETH vault for ape tax
- tokemak weth strategy attached
- deposit limit set to ~50k
=> feat: add weth yvault with tokemak strat

utils/vaults.json
add experimental stargate USDC on ETH
=> feat: add stargate USDC

pages/api/vaults.js
Adding Arbitrum support in the API & reorg get provider
=> Feat: Add arbitrum

contexts/useWeb3.js
Change arbitrum RPC with public one -> https://arbitrum.public-rpc.com
=> Feat: Update Arbitrum RPC

utils/vaults.json
- Add Strategy-Maker-lev-GUNIV3DAIUSDC (0.01% fee pool) to ape.tax
- Rename radioactive dai vault to new vault consistent with the GUNI strategy being the main strategy in the vault.
Repo: https://github.com/mil0xeth/Strategy-Maker-lev-GUNIV3DAIUSDC
Reviews: https://github.com/yearn/yearn-strategies/issues/293
DD: https://hackmd.io/J3yZ4AUKQceRLxG9rFEIiQ
=> feat: add guni

components/Meta.js, components/VaultStrategies.js, package.json, pages/_app.js, pages/api/specificApy.js, public/manifest.json, yarn.lock
=> feat: add meta data

utils/vaults.json
Add 3 strategies to apetax: 
- Strategy-Maker-lev-GUNIV3DAIUSDC (0.01% fee pool) to USDC vault (meet-your-maker)
- Repo: https://github.com/mil0xeth/Strategy-Maker-lev-GUNIV3DAIUSDC/tree/want%3Dusdc%2Cpool%3D0.01%25
- Reviews: https://github.com/yearn/yearn-strategies/issues/324
- DD: https://hackmd.io/J3yZ4AUKQceRLxG9rFEIiQ
- Strategy-Maker-lev-UNIV2DAIUSDC to USDC vault (meet-your-maker)
- Repo: https://github.com/mil0xeth/Strategy-Maker-lev-UNIV2DAIUSDC/tree/main-usdc
- Reviews: https://github.com/yearn/yearn-strategies/issues/332 
- DD: https://hackmd.io/J3yZ4AUKQceRLxG9rFEIiQ (same as above)
- Strategy-Maker-lev-UNIV2DAIUSDC to DAI vault (carpe-daiem)
- Repo: https://github.com/mil0xeth/Strategy-Maker-lev-UNIV2DAIUSDC 
- Reviews: https://github.com/yearn/yearn-strategies/issues/332 …
=> feat: add meet-your-maker & carpe-daiem (+3 strategies in total)

utils/vaults.json
- Updated status as it's been promoted to Yearn
https://yearn.finance/vaults/1/0x378cb52b00F9D0921cb46dFc099CFf73b42419dC
=> fix(vaults): Update status Liquid Spirit vault

pages/index.tsx
This PR has the purpose of improving the header of home page.  Currently, some nav components are overflowing the title when the available screen size decreases.
To address this, I applied media queries to the title.
resolves #203 
The intention to apply this change is solve the issue suggested and make the header looks better in different screen sizes.
After making the changes I ran `yarn dev` and confirmed that everything appeared as expected
N/A
=> chore: Improve responsiveness of header

utils/wagmiChains.ts, utils/wagmiConfig.ts
This PR has the purpose to follow instructions of the issue, moving all the specific chain detail objects existing on the `wagmiConfig.ts` file to a new file called `wagmiChains.ts.`.
resolves #223
This change improves the overall structure of the wagmiConfig file by decreasing its code and facilitating understanding.
N/A
https://wagmi.sh/react/hooks/useNetwork
https://github.com/SmolDapp/smoldapp/blob/main/utils/wagmiChains.ts
=> feat: Moving chain specific details to new 'wagmiChains.ts' file

components/AnimatedWait.tsx, components/InfoMessage.tsx, components/Navbar.tsx, components/ProgressChart.tsx, components/Suspense.tsx, components/VaultActions.tsx, components/VaultDetails.tsx, components/VaultStrategies.tsx, components/VaultWrapper.tsx, contexts/useFactory.tsx, hooks/useFetch.ts, pages/[slug]/index.tsx, pages/_document.tsx, pages/api/tvl.ts, pages/index.tsx, utils/actions.ts, utils/fetch.ts, utils/toWagmiProvider.ts, utils/utils.ts
This PR contains UI and import type changes previously incorporated into `feat/v3-next`. We previously used `feat/v3-next` to separate changes to prevent other branches from growing too large as we worked to ship V3 upgrade. Now that this has been done I believe it's best to separate changes previously committed to `feat/v3-next` branch into smaller related PRs and close the original large PR.
Encapsulate similar changes into small PRs to increase clarity and ease of review
Manually
These commits were previously part of: https://github.com/saltyfacu/ape-tax/pull/236
=> refactor: import types and UI fixes

utils/vaults.json
Add Pearl V3 strategies on Polygon to UI:
DAI-USDR: https://polygonscan.com/address/0xAC8Fe3BaB0Ef1Ea0f9F7A030585bd051693B651c
USDC-USDR: https://polygonscan.com/address/0xA90317B5A98eD903e92f136bC9959636C10367eC
https://github.com/yearn/yearn-strategies/issues/577
Add V3 strategies for testing purposes.
Successful deposit into strategy: https://polygonscan.com/tx/0xcfb551482f920718fc56c84105a268adf129e0f826ca18c37c10446bd4f45920
Pearl exchange: https://www.pearl.exchange/liquidity
=> feat: add pearl strategies (dai,usdc)

utils/vaults.json
Remove vaults moved to prod or shutdown.
=> fix: remove prod vaultS

utils/vaults.json
Add yearn-V3-Stargate-DAI (Polygon) to ape.tax
https://github.com/yearn/yearn-strategies/issues/535
n/a
n/a
n/a
=> feat: add yearn-V3-Stargate-DAI

pages/api/specificApy.ts
=> fix: Facu Infinity

utils/vaults.json
=> feat: ajna weth

utils/vaults.json
=> feat: eure

utils/vaults.json
- Add 3 strategies for Pendle.fi to ape.tax
https://github.com/yearn/yearn-strategies/issues/575
https://github.com/mil0xeth/yearn-v3-Pendle
=> feat: add pendle lp strategies

utils/vaults.json
=> yearn-V3-Ajna-EURe
